# Generated by Django 4.0 on 2022-01-01 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_comment_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_child',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
