# Generated by Django 4.0 on 2022-01-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_comment_child_comment_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_parent',
            new_name='reply_parent',
        ),
    ]
