# Generated by Django 4.0 on 2022-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userblog_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
