# Generated by Django 4.0 on 2022-01-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userblog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
